name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - master
    - feature/*

  paths:
    exclude:
     - doc
     - ReadME.md

pr:
  branches:
    include:
    - master

variables:
- name: vmImage
  value: 'windows-latest'

stages:
- stage: SetupTemplates
  jobs:
  - job: 'SetupTemplates'
    pool:
      vmImage: ${{variables.vmImage}}
    steps:
    - template: 'publishartifacts.yaml'

- stage: DEV
  dependsOn: ['SetupTemplates']
  jobs:
  - deployment: DEV
    variables:
    - template: 'Variables/variables.dev.yaml'
    pool:
        vmImage: ${{variables.vmImage}}
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - template: 'deploy.yaml'