variables:
- name: environmentName
  value: dev
- name: rgName
  value: rg-cctestlink-$(environmentName)
- name: rgLocation
  value: Australia Southeast  
- name: storageAccountName
  value: cctestlink
